### ISSUE TITLE
Crash after running too long

### ISSUE THREAD

**Issue by ski7777** [ski7777/fttxpy#1]
After 1:52h the thread crashes
```
>>> Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/raphael/ftcommunity-TXT/output/target/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
  File "/home/ftc/fttxpy/fttxpy/low_level.py", line 286, in run
    runOK = self.parent.exchangeData()
  File "/home/ftc/fttxpy/fttxpy/low_level.py", line 171, in exchangeData
    execOK = self.X1IOSend()
  File "/home/ftc/fttxpy/fttxpy/low_level.py", line 216, in X1IOSend
    execOK = self.executeX1(data)
  File "/home/ftc/fttxpy/fttxpy/low_level.py", line 146, in executeX1
    execOK, retData = self.connection.X1CMD(data)
  File "/home/ftc/fttxpy/fttxpy/tx_serial.py", line 199, in X1CMD
    execOK = self.sendX1Package(inData)
  File "/home/ftc/fttxpy/fttxpy/tx_serial.py", line 93, in sendX1Package
    PackageTID = self.X1TID.to_bytes(2, byteorder='little')
OverflowError: int too big to convert
```

**Comment by ski7777** [comment]
I should run the TX-C with ROBOPro and wireshark to check the original behavior.
